databases:
  - name: erp-db
    plan: free
    databaseName: erp_backend
    user: erp_user
    region: ohio

services:
  - type: web
    name: erp-web
    env: php
    plan: free
    region: ohio
    buildCommand: "./bin/render-build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: erp-db
          property: connectionString
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: RENDER
        value: "true"
