databases:
  - name: erp-db
    plan: free
    databaseName: erp_backend
    user: erp_user
    region: ohio

services:
  - type: web
    name: erp-web
    env: docker
    plan: free
    region: ohio
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: erp-db
          property: connectionString
      - key: APP_KEY
        value: base64:j4FE1w0m4tP5kXM5kIxHcbwZHRX1jvenP68w87ClK74=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: RENDER
        value: "true"
